In [ ]:
import numpy as np

In [6]:
list=[1,2,3,4,5]

In [8]:
list[2::-1]

[3, 2, 1]

In [ ]:
type(list)

In [ ]:
arr=np.array(list)

In [36]:
type(arr)

numpy.ndarray

In [37]:
list=([1,2,3,4,7],[2,4,5,9,6],[8,7,6,6,5],[8,2,9,5,6])

In [38]:
arr1=np.array(list)

In [39]:
arr1

array([[1, 2, 3, 4, 7],
       [2, 4, 5, 9, 6],
       [8, 7, 6, 6, 5],
       [8, 2, 9, 5, 6]])

In [40]:
arr1.shape

(4, 5)

In [41]:
arr1[0:2,2:5]

array([[3, 4, 7],
       [5, 9, 6]])

In [42]:
arr1[0:2,1:3]

array([[2, 3],
       [4, 5]])

In [43]:
arr1.diagonal()

array([1, 4, 6, 5])

In [44]:
arr1[:][3]

array([8, 2, 9, 5, 6])

In [45]:
arr1[[0,1,2,3],[1,3,0,3]]

array([2, 9, 8, 5])

In [46]:
list2 =[arr1[0,0],arr1[0,2],arr1[0,4]]



In [47]:
list2

[1, 3, 7]

In [48]:
list1=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [49]:
arr2=np.array(list1)

In [50]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [51]:
arr2[[0,1,3],[2,3,3]]

array([ 3,  8, 16])

In [52]:
arrange=np.arange(0,16)

In [53]:
arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
arrange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
arrange.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [36]:
arrange.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [37]:
np.random.rand(2,3)

array([[0.82937802, 0.36066356, 0.1243319 ],
       [0.41020277, 0.77326228, 0.19610245]])

In [40]:
np.random.randint(0,100,20).reshape(4,5)

array([[86,  0, 40, 29, 75],
       [ 8, 67, 65, 93, 14],
       [72, 37, 16, 71, 18],
       [ 3, 38, 43, 11, 16]])

In [42]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [43]:
p=np.arange(10,21)

In [44]:
p

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
q=p.ravel()

In [46]:
q

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [47]:
q[3]=28

In [48]:
q

array([10, 11, 12, 28, 14, 15, 16, 17, 18, 19, 20])

In [49]:
p

array([10, 11, 12, 28, 14, 15, 16, 17, 18, 19, 20])

In [50]:
a=np.arange(0,4).reshape(2,2)

In [51]:
a


array([[0, 1],
       [2, 3]])

In [53]:
b=np.arange(4,8).reshape(2,2)

In [54]:
b

array([[4, 5],
       [6, 7]])

In [56]:
c=np.concatenate((a,b))

In [57]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [61]:
c=np.concatenate((a,b),axis=1)

In [59]:
c

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [62]:
d=c.transpose()

In [64]:
d

array([[0, 2],
       [1, 3],
       [4, 6],
       [5, 7]])

In [8]:
import pandas as pd

In [9]:
df2=pd.DataFrame([[1,2,3],[5,6,7]],index="a b".split(),columns="A B C".split())

In [10]:
df1 = pd.DataFrame([[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]], index = "A B C D".split(),columns = "a b c d".split())


In [11]:
df2

A  B  C
a  1  2  3
b  5  6  7

In [12]:
df1

a   b   c   d
A   1   2   3   4
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [13]:
df1.loc['A']

a    1
b    2
c    3
d    4
Name: A, dtype: int64

In [14]:
df1[['a','b']]

a   b
A   1   2
B   4   5
C   8   9
D  12  13

In [15]:
df1.reset_index()

index   a   b   c   d
0     A   1   2   3   4
1     B   4   5   6   7
2     C   8   9  10  11
3     D  12  13  14  15

In [16]:
df1.reset_index()

index   a   b   c   d
0     A   1   2   3   4
1     B   4   5   6   7
2     C   8   9  10  11
3     D  12  13  14  15

In [17]:
newind="ca ua na da".split()

In [18]:
newind

['ca', 'ua', 'na', 'da']

In [21]:
df1["newindex"]=newind

In [22]:
df1.set_index("newindex")

a   b   c   d
newindex                
ca         1   2   3   4
ua         4   5   6   7
na         8   9  10  11
da        12  13  14  15

In [23]:
df1.head(2)

a  b  c  d newindex
A  1  2  3  4       ca
B  4  5  6  7       ua

In [24]:
df1.tail()

a   b   c   d newindex
A   1   2   3   4       ca
B   4   5   6   7       ua
C   8   9  10  11       na
D  12  13  14  15       da

In [25]:
df1.tail(2)

a   b   c   d newindex
C   8   9  10  11       na
D  12  13  14  15       da

In [26]:
df1['a'].unique()

array([ 1,  4,  8, 12], dtype=int64)

In [27]:
df1['a'].value_counts()

12    1
4     1
1     1
8     1
Name: a, dtype: int64

In [29]:
df1.describe()

a          b          c          d
count   4.000000   4.000000   4.000000   4.000000
mean    6.250000   7.250000   8.250000   9.250000
std     4.787136   4.787136   4.787136   4.787136
min     1.000000   2.000000   3.000000   4.000000
25%     3.250000   4.250000   5.250000   6.250000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000

In [30]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, A to D
Data columns (total 5 columns):
a           4 non-null int64
b           4 non-null int64
c           4 non-null int64
d           4 non-null int64
newindex    4 non-null object
dtypes: int64(4), object(1)
memory usage: 352.0+ bytes


In [55]:
df=pd.DataFrame({'A':[1,2,np.nan],'B':[4,np.nan,np.nan],'C':[1,4,34]})

In [56]:
df

A    B   C
0  1.0  4.0   1
1  2.0  NaN   4
2  NaN  NaN  34

In [57]:
df.isnull().any

<bound method DataFrame.any of        A      B      C
0  False  False  False
1  False   True  False
2   True   True  False>

In [58]:
df.isnull().any()

A     True
B     True
C    False
dtype: bool

In [59]:
df.isnull().sum()

A    1
B    2
C    0
dtype: int64

In [65]:
dad=pd.DataFrame({'A':[1,3,4,np.nan,np.nan,np.nan,9,3,np.nan,7],'c':[7,8,5,6,4,9,0,3,4,7],'d':[np.nan,6,2,8,2,np.nan,3,7,5,np.nan],'e':[1,2,3,4,5,6,7,8,9,11]})

In [66]:
dad

A  c    d   e
0  1.0  7  NaN   1
1  3.0  8  6.0   2
2  4.0  5  2.0   3
3  NaN  6  8.0   4
4  NaN  4  2.0   5
5  NaN  9  NaN   6
6  9.0  0  3.0   7
7  3.0  3  7.0   8
8  NaN  4  5.0   9
9  7.0  7  NaN  11

In [69]:
dad['A'].fillna(dad['A'].mean(),inplace=True)

In [71]:
dad

A  c    d   e
0  1.0  7  NaN   1
1  3.0  8  6.0   2
2  4.0  5  2.0   3
3  4.5  6  8.0   4
4  4.5  4  2.0   5
5  4.5  9  NaN   6
6  9.0  0  3.0   7
7  3.0  3  7.0   8
8  4.5  4  5.0   9
9  7.0  7  NaN  11

In [78]:
dad['d'].fillna(dad['d'].mode()[0],inplace=True)

In [79]:
dad

A  c    d   e
0  1.0  7  2.0   1
1  3.0  8  6.0   2
2  4.0  5  2.0   3
3  4.5  6  8.0   4
4  4.5  4  2.0   5
5  4.5  9  2.0   6
6  9.0  0  3.0   7
7  3.0  3  7.0   8
8  4.5  4  5.0   9
9  7.0  7  2.0  11