# Steps involved in Data Processing

In [1]:
#1.import libraries

import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
#2.Reading the dataset

data=pd.read_csv(r"Downloads\bank.csv")


In [3]:
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [4]:
data.head(2)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   
1   56  admin.  married  secondary      no       45      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes

In [6]:
#step4.converting textual to numerical data

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['job'] = le.fit_transform(data['job'] )
data['marital'] = le.fit_transform(data['marital'] )
data['education'] = le.fit_transform(data['education'] )
data['default'] = le.fit_transform(data['default'] )
data['housing'] = le.fit_transform(data['housing'] )
data['contact'] = le.fit_transform(data['contact'] )
data['month'] = le.fit_transform(data['month'] )
data['poutcome'] = le.fit_transform(data['poutcome'] )
data['loan'] = le.fit_transform(data['loan'] )
data['deposit'] = le.fit_transform(data['deposit'] )



In [7]:
data.head(5)

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   
1   56    0        1          1        0       45        0     0        2   
2   41    9        1          1        0     1270        1     0        2   
3   55    7        1          1        0     2476        1     0        2   
4   54    0        1          2        0      184        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1  
1    5      8      1467         1     -1         0         3        1  
2    5      8      1389         1     -1         0         3        1  
3    5      8       579         1     -1         0         3        1  
4    5      8       673         2     -1         0         3        1

In [12]:
#5.splitting the dataset
x=data.iloc[:,0:16].values


In [13]:
y=data.iloc[:,16].values

In [14]:
x.shape

(11162, 16)

In [15]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [16]:
data.head(1)

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1

In [ ]:
x.shape

In [19]:
#6.Converting numerically converted to binary
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
a=one.fit_transform(x[:,1:2]).toarray()
b=one.fit_transform(x[:,2:3]).toarray()
c=one.fit_transform(x[:,3:4]).toarray()
e=one.fit_transform(x[:,8:9]).toarray()
f=one.fit_transform(x[:,10:11]).toarray()
h=one.fit_transform(x[:,15:16]).toarray()

x=np.delete(x,[1,2,3,8,10,15],axis=1)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used

In [20]:
x.shape

(11162, 10)

In [21]:
x=np.concatenate((a,b,c,e,f,h,x),axis=1)

In [22]:
x.shape

(11162, 48)

In [23]:
#7split the data in to train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [24]:
x_test.shape

(2233, 48)

In [25]:
x_train.shape

(8929, 48)

In [26]:
y_test.shape

(2233,)

In [27]:
y_train.shape

(8929,)

In [28]:
x_train

array([[ 0.,  0.,  0., ...,  1., -1.,  0.],
       [ 0.,  0.,  0., ...,  1., -1.,  0.],
       [ 0.,  1.,  0., ...,  5., -1.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  8., -1.,  0.],
       [ 1.,  0.,  0., ...,  1., -1.,  0.],
       [ 0.,  0.,  0., ...,  1., -1.,  0.]])

In [29]:
#8.feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [30]:
x_train

array([[-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192,  2.18530314, -0.17658264, ...,  0.92827075,
        -0.48428507, -0.35888264],
       ...,
       [-0.37172192, -0.45760242, -0.17658264, ...,  2.04743488,
        -0.48428507, -0.35888264],
       [ 2.69018306, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264]])

In [32]:
data.describe()

age           job       marital     education       default  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948      4.487905      1.199337      1.285164      0.015051   
std       11.913369      3.225132      0.625552      0.749478      0.121761   
min       18.000000      0.000000      0.000000      0.000000      0.000000   
25%       32.000000      1.000000      1.000000      1.000000      0.000000   
50%       39.000000      4.000000      1.000000      1.000000      0.000000   
75%       49.000000      7.000000      2.000000      2.000000      0.000000   
max       95.000000     11.000000      2.000000      3.000000      1.000000   

            balance       housing          loan       contact           day  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean    1528.530550      0.473123      0.130801      0.489697     15.658036   
std     3225.415868      0.499299      0.337198      0.818724      8.420740   
min    -6847.000000      0.000000      0.000000      0.000000      1.000000   
25%      122.000000      0.000000      0.000000      0.000000      8.000000   
50%      550.000000      0.000000      0.000000      0.000000     15.000000   
75%     1708.000000      1.000000      0.000000      1.000000     22.000000   
max    81204.000000      1.000000      1.000000      2.000000     31.000000   

              month      duration      campaign         pdays      previous  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean       5.445709    371.918473      2.508421     51.330407      0.832557   
std        3.191939    347.018846      2.722077    108.758282      2.292007   
min        0.000000      2.000000      1.000000     -1.000000      0.000000   
25%        3.000000    138.000000      1.000000     -1.000000      0.000000   
50%        6.000000    255.000000      2.000000     -1.000000      0.000000   
75%        8.000000    496.000000      3.000000     20.750000      1.000000   
max       11.000000   3881.000000     63.000000    854.000000     58.000000   

           poutcome       deposit  
count  11162.000000  11162.000000  
mean       2.477782      0.473840  
std        1.002952      0.499338  
min        0.000000      0.000000  
25%        2.000000      0.000000  
50%        3.000000      0.000000  
75%        3.000000      1.000000  
max        3.000000      1.000000