In [1]:
#import libraries
import pandas as pd
import numpy as np

In [2]:
#step 2-reading the dataset
 
dataset=pd.read_csv(r"Downloads\churn_Modelling.csv")

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender             False
Age                 True
Tenure             False
Balance             True
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [5]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0   
1          2    15647311      Hill          225     Spain  Female  41.0   
2          3    15619304      Onio          629    France  Female  42.0   
3          4    15701354      Boni          699    France  Female  39.0   
4          5    15737888  Mitchell          850       NaN  Female  43.0   
5          6    15574012       Chu          645     Spain    Male  44.0   
6          7    15592531  Bartlett          822    France    Male  50.0   
7          8    15656148    Obinna          376   Germany  Female  29.0   
8          9    15792365        He          501    France    Male   NaN   
9         10    15592389        H?          684    France    Male  27.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [6]:
dataset['Geography'].fillna(dataset['Geography'].mode()[0],inplace=True)
dataset['Age'].fillna(dataset['Age'].mean(),inplace=True)
dataset['Balance'].fillna(dataset['Balance'].median(),inplace=True)

In [7]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender        Age  \
0          1    15634602  Hargrave          619    France  Female  42.000000   
1          2    15647311      Hill          225     Spain  Female  41.000000   
2          3    15619304      Onio          629    France  Female  42.000000   
3          4    15701354      Boni          699    France  Female  39.000000   
4          5    15737888  Mitchell          850    France  Female  43.000000   
5          6    15574012       Chu          645     Spain    Male  44.000000   
6          7    15592531  Bartlett          822    France    Male  50.000000   
7          8    15656148    Obinna          376   Germany  Female  29.000000   
8          9    15792365        He          501    France    Male  38.921292   
9         10    15592389        H?          684    France    Male  27.000000   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [8]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [9]:
#textual data to numerical data

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['Geography']=le.fit_transform(dataset['Geography'])



In [10]:
dataset['Gender']=le.fit_transform(dataset['Gender'])

In [11]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender        Age  \
0          1    15634602  Hargrave          619          0       0  42.000000   
1          2    15647311      Hill          225          2       0  41.000000   
2          3    15619304      Onio          629          0       0  42.000000   
3          4    15701354      Boni          699          0       0  39.000000   
4          5    15737888  Mitchell          850          0       0  43.000000   
5          6    15574012       Chu          645          2       1  44.000000   
6          7    15592531  Bartlett          822          0       1  50.000000   
7          8    15656148    Obinna          376          1       0  29.000000   
8          9    15792365        He          501          0       1  38.921292   
9         10    15592389        H?          684          0       1  27.000000   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [12]:
#to grab the values-splitting the dataset step 5
x=dataset.iloc[:,3:13].values
#.values because onehotencoder takes only arrays
#hence dataset is being converted to numpy arrays

In [13]:
y=dataset.iloc[:,13].values

In [14]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [15]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [16]:
type(x)

numpy.ndarray

In [17]:
x.shape

(10000, 10)

In [18]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(x[:,1:2]).toarray()

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [19]:
x=np.delete(x,1,axis=1)
x

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 0.0000000e+00, 4.1000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 3.6000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 2.8000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [20]:
x=np.concatenate((z,x),axis=1)

In [21]:
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [22]:
#due to delete and concatenate it has changed from 10 to 12
#as geography is replaced by z 1 2 
x.shape

(10000, 12)

In [23]:
y.shape

(10000,)

In [24]:
#split the data in to train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [25]:
y_test.shape

(2000,)

In [26]:
x_train.shape

(8000, 12)

In [27]:
y_train.shape

(8000,)

In [28]:
from sklearn.model_selection import train_test_split
for i in range(5):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
    print("x without random state",i,x_train)
for i in range(5):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
    print("x without random state",i,x_train)    

x without random state 0 [[1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 8.8146900e+03]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 9.4951270e+04]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 7.9775190e+04]
 ...
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 4.6416360e+04]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  1.0000000e+00 1.2996456e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 7.0954410e+04]]
x without random state 1 [[0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 3.9356380e+04]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  1.0000000e+00 7.3470980e+04]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 1.7991398e+05]
 ...
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 ... 1.0000000e+00
  0.0000000e+00 1.7864273e+05]
 [1.00000

In [29]:
x_train[:,5:10]

array([[3.4000000e+01, 5.0000000e+00, 0.0000000e+00, 2.0000000e+00,
        1.0000000e+00],
       [4.2000000e+01, 1.0000000e+00, 7.5681520e+04, 1.0000000e+00,
        1.0000000e+00],
       [2.9000000e+01, 2.0000000e+00, 1.1236734e+05, 1.0000000e+00,
        1.0000000e+00],
       ...,
       [3.5000000e+01, 5.0000000e+00, 1.6127405e+05, 2.0000000e+00,
        1.0000000e+00],
       [3.8000000e+01, 9.0000000e+00, 0.0000000e+00, 2.0000000e+00,
        1.0000000e+00],
       [4.8000000e+01, 1.0000000e+00, 1.0807633e+05, 1.0000000e+00,
        1.0000000e+00]])

In [30]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [31]:
x_train

array([[-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [32]:
dataset.describe()

RowNumber    CustomerId   CreditScore     Geography        Gender  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.503200      0.746100      0.545700   
std     2886.89568  7.193619e+04     96.734833      0.827468      0.497932   
min        1.00000  1.556570e+07    225.000000      0.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000      0.000000      0.000000   
50%     5000.50000  1.569074e+07    652.000000      0.000000      1.000000   
75%     7500.25000  1.575323e+07    718.000000      1.000000      1.000000   
max    10000.00000  1.581569e+07    850.000000      2.000000      1.000000   

                Age        Tenure        Balance  NumOfProducts    HasCrCard  \
count  10000.000000  10000.000000   10000.000000   10000.000000  10000.00000   
mean      38.921292      5.012800   76485.406478       1.530200      0.70550   
std       10.487683      2.892174   62397.226313       0.581654      0.45584   
min       18.000000      0.000000       0.000000       1.000000      0.00000   
25%       32.000000      3.000000       0.000000       1.000000      0.00000   
50%       37.000000      5.000000   97188.620000       1.000000      1.00000   
75%       44.000000      7.000000  127644.240000       2.000000      1.00000   
max       92.000000     10.000000  250898.090000       4.000000      1.00000   

       IsActiveMember  EstimatedSalary        Exited  
count    10000.000000     10000.000000  10000.000000  
mean         0.515100    100090.239881      0.203700  
std          0.499797     57510.492818      0.402769  
min          0.000000        11.580000      0.000000  
25%          0.000000     51002.110000      0.000000  
50%          1.000000    100193.915000      0.000000  
75%          1.000000    149388.247500      0.000000  
max          1.000000    199992.480000      1.000000

In [33]:
x_train

array([[-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [34]:
42-38.9/10

38.11

In [36]:
#step1:importing libraries
import keras
from keras.layers import Dense#used for input layer output layer and hidden layer
from keras.models import Sequential#type of model

Using TensorFlow backend.


In [37]:
#step2:initializing the model
model=Sequential()

In [38]:
#step3:add input layer
model.add(Dense(units=12,init="random_uniform",activation="relu"))#units are how many inputs we are going to give i.e 12 inputs are ther in input layer


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=12, activation="relu", kernel_initializer="random_uniform")`
  


In [40]:
#4.adding hidden layer
model.add(Dense(units=24,init="random_uniform",activation="relu"))

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=24, activation="relu", kernel_initializer="random_uniform")`
  


In [41]:
#5.adding output layer
model.add(Dense(units=1,init="random_uniform",activation="sigmoid"))

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="random_uniform")`
  


In [44]:
#step6:configure the learning process
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
#optimizer is the gradient ie mini batch 
#loss is the cost function
#metrice for accuracy from confusion matrix


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [45]:
model.fit(x_train,y_train,batch_size=32,epochs=100)
#every epho the rows we are considering as 32 rows for it from x_train and y_train
#due to batch wise 86%
#batch size=8,16,32,128,256,1204


Epoch 1/100
8000/8000 [==============================] - 3s 351us/step - loss: 0.5160 - accuracy: 0.7954
Epoch 2/100
8000/8000 [==============================] - 0s 55us/step - loss: 0.4314 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 49us/step - loss: 0.4256 - accuracy: 0.7970
Epoch 4/100
8000/8000 [==============================] - 0s 61us/step - loss: 0.4206 - accuracy: 0.8201
Epoch 5/100
8000/8000 [==============================] - 0s 51us/step - loss: 0.4161 - accuracy: 0.8255
Epoch 6/100
8000/8000 [==============================] - 0s 54us/step - loss: 0.4141 - accuracy: 0.8294
Epoch 7/100
8000/8000 [==============================] - 0s 49us/step - loss: 0.4107 - accuracy: 0.8321
Epoch 8/100
8000/8000 [==============================] - 0s 55us/step - loss: 0.4081 - accuracy: 0.8331
Epoch 9/100
8000/8000 [==============================] - 0s 49us/step - loss: 0.4061 - accuracy: 0.8336
Epoch 10/100
8000/8000 [==============================] - 0s 4

8000/8000 [==============================] - 1s 110us/step - loss: 0.3328 - accuracy: 0.8644
Epoch 78/100
8000/8000 [==============================] - 1s 63us/step - loss: 0.3331 - accuracy: 0.8622
Epoch 79/100
8000/8000 [==============================] - 0s 54us/step - loss: 0.3326 - accuracy: 0.8636
Epoch 80/100
8000/8000 [==============================] - 0s 57us/step - loss: 0.3333 - accuracy: 0.8615
Epoch 81/100
8000/8000 [==============================] - 1s 92us/step - loss: 0.3315 - accuracy: 0.8636
Epoch 82/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.3328 - accuracy: 0.8643
Epoch 83/100
8000/8000 [==============================] - 0s 51us/step - loss: 0.3314 - accuracy: 0.8635
Epoch 84/100
8000/8000 [==============================] - 1s 65us/step - loss: 0.3318 - accuracy: 0.8633
Epoch 85/100
8000/8000 [==============================] - 1s 66us/step - loss: 0.3309 - accuracy: 0.8639
Epoch 86/100
8000/8000 [==============================] - 0s 55us/

In [46]:
y_pred=model.predict(x_test)

In [47]:
y_pred#as we gave sigmoid we got values from between 0 to 1

array([[0.20005289],
       [0.3151983 ],
       [0.11418912],
       ...,
       [0.2422669 ],
       [0.13777032],
       [0.20313111]], dtype=float32)

In [48]:
y_pred=(y_pred>0.5)
#>0.5 =1
#<0.5=1
#because of sigmoid function 
#we gave so apply threshold to get as o or 1

In [49]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [50]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender   Age  \
0          1    15634602  Hargrave          619          0       0  42.0   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [52]:
y_p=model.predict(sc.transform(np.array([[1,0,0,619,0,42,8,12345,1,1,1,1234567]])))
#if we apply scaling to the inputs we need to do this to convert
#to original form
#we can use np.array or may not use np.array


In [53]:
y_p

array([[0.00258024]], dtype=float32)

In [54]:
y_p=y_p>0.5

In [55]:
y_p
#he will leave the office

array([[False]])

In [59]:
keras.__version__

'2.3.1'

In [58]:
import tensorflow
tensorflow.__version__

'1.14.0'

In [60]:
import keras
keras.__version__

'2.3.1'