In [ ]:
#import libraries
import pandas as pd
import numpy as np

In [ ]:
#step 2-reading the dataset

dataset=pd.read_csv(r"Downloads\churn_Modelling.csv")

In [ ]:
type(dataset)

In [ ]:
dataset.isnull().any()

In [ ]:
dataset.head(10)

In [ ]:
dataset['Geography'].fillna(dataset['Geography'].mode()[0],inplace=True)
dataset['Age'].fillna(dataset['Age'].mean(),inplace=True)
dataset['Balance'].fillna(dataset['Balance'].median(),inplace=True)

In [ ]:
dataset.head(10)

In [ ]:
dataset.isnull().any()

In [9]:
#textual data to numerical data

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['Geography']=le.fit_transform(dataset['Geography'])



In [10]:
dataset['Gender']=le.fit_transform(dataset['Gender'])

In [11]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender        Age  \
0          1    15634602  Hargrave          619          0       0  42.000000   
1          2    15647311      Hill          225          2       0  41.000000   
2          3    15619304      Onio          629          0       0  42.000000   
3          4    15701354      Boni          699          0       0  39.000000   
4          5    15737888  Mitchell          850          0       0  43.000000   
5          6    15574012       Chu          645          2       1  44.000000   
6          7    15592531  Bartlett          822          0       1  50.000000   
7          8    15656148    Obinna          376          1       0  29.000000   
8          9    15792365        He          501          0       1  38.921292   
9         10    15592389        H?          684          0       1  27.000000   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [12]:
#to grab the values-splitting the dataset step 5
x=dataset.iloc[:,3:13].values
#.values because onehotencoder takes only arrays
#hence dataset is being converted to numpy arrays

In [13]:
y=dataset.iloc[:,13].values

In [14]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [15]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [16]:
type(x)

numpy.ndarray

In [17]:
x.shape

(10000, 10)

In [18]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(x[:,1:2]).toarray()

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [19]:
x=np.delete(x,1,axis=1)
x

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 0.0000000e+00, 4.1000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 3.6000000e+01, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 2.8000000e+01, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [20]:
x=np.concatenate((z,x),axis=1)

In [21]:
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [22]:
#due to delete and concatenate it has changed from 10 to 12
#as geography is replaced by z 1 2 
x.shape

(10000, 12)

In [23]:
y.shape

(10000,)

In [24]:
#split the data in to train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [26]:
y_test.shape

(2000,)

In [27]:
x_train.shape

(8000, 12)

In [28]:
y_train.shape

(8000,)

In [ ]:
from sklearn.model_selection import train_test_split
for i in range(5):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
    print("x without random state",i,x_train)
for i in range(5):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
    print("x without random state",i,x_train)    

In [30]:
x_train[:,5:10]

array([[3.4000000e+01, 5.0000000e+00, 0.0000000e+00, 2.0000000e+00,
        1.0000000e+00],
       [4.2000000e+01, 1.0000000e+00, 7.5681520e+04, 1.0000000e+00,
        1.0000000e+00],
       [2.9000000e+01, 2.0000000e+00, 1.1236734e+05, 1.0000000e+00,
        1.0000000e+00],
       ...,
       [3.5000000e+01, 5.0000000e+00, 1.6127405e+05, 2.0000000e+00,
        1.0000000e+00],
       [3.8000000e+01, 9.0000000e+00, 0.0000000e+00, 2.0000000e+00,
        1.0000000e+00],
       [4.8000000e+01, 1.0000000e+00, 1.0807633e+05, 1.0000000e+00,
        1.0000000e+00]])

In [35]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [37]:
x_train

array([[-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [47]:
dataset.describe()

RowNumber    CustomerId   CreditScore     Geography        Gender  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.503200      0.746100      0.545700   
std     2886.89568  7.193619e+04     96.734833      0.827468      0.497932   
min        1.00000  1.556570e+07    225.000000      0.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000      0.000000      0.000000   
50%     5000.50000  1.569074e+07    652.000000      0.000000      1.000000   
75%     7500.25000  1.575323e+07    718.000000      1.000000      1.000000   
max    10000.00000  1.581569e+07    850.000000      2.000000      1.000000   

                Age        Tenure        Balance  NumOfProducts    HasCrCard  \
count  10000.000000  10000.000000   10000.000000   10000.000000  10000.00000   
mean      38.921292      5.012800   76485.406478       1.530200      0.70550   
std       10.487683      2.892174   62397.226313       0.581654      0.45584   
min       18.000000      0.000000       0.000000       1.000000      0.00000   
25%       32.000000      3.000000       0.000000       1.000000      0.00000   
50%       37.000000      5.000000   97188.620000       1.000000      1.00000   
75%       44.000000      7.000000  127644.240000       2.000000      1.00000   
max       92.000000     10.000000  250898.090000       4.000000      1.00000   

       IsActiveMember  EstimatedSalary        Exited  
count    10000.000000     10000.000000  10000.000000  
mean         0.515100    100090.239881      0.203700  
std          0.499797     57510.492818      0.402769  
min          0.000000        11.580000      0.000000  
25%          0.000000     51002.110000      0.000000  
50%          1.000000    100193.915000      0.000000  
75%          1.000000    149388.247500      0.000000  
max          1.000000    199992.480000      1.000000

In [49]:
x_train

array([[-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [50]:
42-38.9/10

38.11